'''
Created on Nov 9, 2023

@author: immanueltrummer
'''
import argparse
import openai
import time


def analyze_image(image_url, question):
    """ Use language model to answer question about image.
    
    Args:
        image_url: URL leading to image.
        question: question about image.
    
    Returns:
        Answer generated by the language model.
    """
    for nr_retries in range(1, 4):
        #response = openai.ChatCompletion.create(
        response = client.chat.completions.create(
            model='gpt-4-vision-preview',
            messages=[
                {'role':'user', 'content':[
                    {'type':'text', 'text':question},
                    {'type':'image_url', 'image_url':{
                        'url':image_url
                        }
                    }]
                }]
            )
        #return response['choices'][0]['message']['content']
        return response.choices[0].message.content            


if __name__ == '__main__':
    
    parser = argparse.ArgumentParser()
    parser.add_argument('openaikey', type=str, help='OpenAI access key')
    parser.add_argument('imageurl', type=str, help='URL to image')
    parser.add_argument('question', type=str, help='Question about the image')
    args = parser.parse_args()

    openai.api_key = args.openaikey

    # new
    from openai import OpenAI
    client = OpenAI(api_key=args.openaikey,)  # this is also the default, it can be omitted

    answer = analyze_image(args.imageurl, args.question)
    print(answer)